# Generated by Selenium IDE
import time

from selenium.common.exceptions import NoSuchElementException

from core.environment.host import get_host_for_selenium_testing
from core.selenium.common import initialize_driver


class TestFakenodotest:
    def setup_method(self, method):
        self.driver = initialize_driver()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_fakenodotest(self):
        host = get_host_for_selenium_testing()

        self.driver.get(f"{host}/fakenodo")
        self.driver.set_window_size(1854, 1048)
        time.sleep(2)

        try:
            pass

        except NoSuchElementException:
            raise AssertionError("Test failed!")
