# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By


class TestFakenodotest:
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_fakenodotest(self):
        self.driver.get("http://localhost:5000/")
        self.driver.set_window_size(1854, 1048)
        self.driver.find_element(By.LINK_TEXT, "Sample dataset 4").click()
        self.driver.find_element(By.CSS_SELECTOR, ".sidebar-item:nth-child(6) .align-middle:nth-child(2)").click()
        self.driver.find_element(By.ID, "title").click()
        self.driver.find_element(By.ID, "title").send_keys("asdfghgfds")
        self.driver.find_element(By.ID, "desc").click()
        self.driver.find_element(By.ID, "desc").send_keys("asdfghjhgfds")
        self.driver.find_element(By.ID, "myDropzone").click()
        self.driver.find_element(By.LINK_TEXT, "asdfghgfds").click()
