"""empty message

Revision ID: 002
Revises: 001
Create Date: 2025-12-12 17:58:41.622390

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '002'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bm_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solver', sa.Text(), nullable=True),
    sa.Column('not_solver', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bm_meta_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('csv_filename', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('league', sa.Enum('ACB', 'NBA', 'LEGA', 'EUROLEAGUE', 'OTHER', name='league'), nullable=False),
    sa.Column('tags', sa.String(length=120), nullable=True),
    sa.Column('csv_version', sa.String(length=120), nullable=True),
    sa.Column('bm_metrics_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bm_metrics_id'], ['bm_metrics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('basket_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_set_id', sa.Integer(), nullable=False),
    sa.Column('bm_meta_data_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bm_meta_data_id'], ['bm_meta_data.id'], ),
    sa.ForeignKeyConstraint(['data_set_id'], ['data_set.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ds_meta_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('league', sa.Enum('ACB', 'NBA', 'LEGA', 'EUROLEAGUE', 'OTHER', name='league'), nullable=False))
        batch_op.drop_column('publication_doi')
        batch_op.drop_column('dataset_doi')
        batch_op.drop_column('publication_type')

    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('basket_model_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('file_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'basket_model', ['basket_model_id'], ['id'])
        batch_op.drop_column('feature_model_id')

    op.drop_table('feature_model')
    op.drop_table('author')
    op.drop_table('fm_meta_data')
    op.drop_table('doi_mapping')
    op.drop_table('webhook')
    op.drop_table('fm_metrics')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feature_model_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('file_ibfk_1'), 'feature_model', ['feature_model_id'], ['id'])
        batch_op.drop_column('basket_model_id')

    with op.batch_alter_table('ds_meta_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publication_type', mysql.ENUM('NONE', 'ANNOTATION_COLLECTION', 'BOOK', 'BOOK_SECTION', 'CONFERENCE_PAPER', 'DATA_MANAGEMENT_PLAN', 'JOURNAL_ARTICLE', 'PATENT', 'PREPRINT', 'PROJECT_DELIVERABLE', 'PROJECT_MILESTONE', 'PROPOSAL', 'REPORT', 'SOFTWARE_DOCUMENTATION', 'TAXONOMIC_TREATMENT', 'TECHNICAL_NOTE', 'THESIS', 'WORKING_PAPER', 'OTHER'), nullable=False))
        batch_op.add_column(sa.Column('dataset_doi', mysql.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('publication_doi', mysql.VARCHAR(length=120), nullable=True))
        batch_op.drop_column('league')

    op.create_table('feature_model',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('data_set_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('fm_meta_data_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['data_set_id'], ['data_set.id'], name=op.f('feature_model_ibfk_1')),
    sa.ForeignKeyConstraint(['fm_meta_data_id'], ['fm_meta_data.id'], name=op.f('feature_model_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('fm_meta_data',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('uvl_filename', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('publication_type', mysql.ENUM('NONE', 'ANNOTATION_COLLECTION', 'BOOK', 'BOOK_SECTION', 'CONFERENCE_PAPER', 'DATA_MANAGEMENT_PLAN', 'JOURNAL_ARTICLE', 'PATENT', 'PREPRINT', 'PROJECT_DELIVERABLE', 'PROJECT_MILESTONE', 'PROPOSAL', 'REPORT', 'SOFTWARE_DOCUMENTATION', 'TAXONOMIC_TREATMENT', 'TECHNICAL_NOTE', 'THESIS', 'WORKING_PAPER', 'OTHER'), nullable=False),
    sa.Column('publication_doi', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('tags', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('uvl_version', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('fm_metrics_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fm_metrics_id'], ['fm_metrics.id'], name='fm_meta_data_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('fm_metrics',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('solver', mysql.TEXT(), nullable=True),
    sa.Column('not_solver', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('webhook',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('doi_mapping',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('dataset_doi_old', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('dataset_doi_new', mysql.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('author',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('affiliation', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('orcid', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('ds_meta_data_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('fm_meta_data_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ds_meta_data_id'], ['ds_meta_data.id'], name=op.f('author_ibfk_1')),
    sa.ForeignKeyConstraint(['fm_meta_data_id'], ['fm_meta_data.id'], name=op.f('author_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('basket_model')
    op.drop_table('bm_meta_data')
    op.drop_table('bm_metrics')
    # ### end Alembic commands ###
