"""fakenodo

Revision ID: 003
Revises: 002
Create Date: 2025-12-13 19:10:28.234928

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "003"
down_revision = "002"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fake_deposition",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("conceptrecid", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("upload_type", sa.String(length=50), nullable=True),
        sa.Column("creators", sa.Text(), nullable=True),
        sa.Column("keywords", sa.Text(), nullable=True),
        sa.Column("access_right", sa.String(length=20), nullable=True),
        sa.Column("license", sa.String(length=50), nullable=True),
        sa.Column("doi", sa.String(length=100), nullable=True),
        sa.Column("state", sa.String(length=20), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.Column("modified", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("conceptrecid"),
    )
    op.create_table("fakenodo", sa.Column("id", sa.Integer(), nullable=False), sa.PrimaryKeyConstraint("id"))
    op.create_table(
        "fake_file",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deposition_id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("filesize", sa.Integer(), nullable=False),
        sa.Column("checksum", sa.String(length=100), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["deposition_id"],
            ["fake_deposition.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("fake_file")
    op.drop_table("fakenodo")
    op.drop_table("fake_deposition")
    # ### end Alembic commands ###
