"""003

Revision ID: 25b6dafcf248
Revises: 002
Create Date: 2025-12-13 17:50:26.711899

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '25b6dafcf248'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fake_file')
    op.drop_table('fakenodo')
    with op.batch_alter_table('fake_deposition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('conceptrecid'))

    op.drop_table('fake_deposition')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fake_deposition',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('conceptrecid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('upload_type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('creators', mysql.TEXT(), nullable=True),
    sa.Column('keywords', mysql.TEXT(), nullable=True),
    sa.Column('access_right', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('license', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('doi', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('state', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('created', mysql.DATETIME(), nullable=True),
    sa.Column('modified', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('fake_deposition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('conceptrecid'), ['conceptrecid'], unique=True)

    op.create_table('fakenodo',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('fake_file',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('deposition_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('filename', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('filesize', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('checksum', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('created', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['deposition_id'], ['fake_deposition.id'], name=op.f('fake_file_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
