# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By


class TestCheckFail:
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_checkFail(self):
        self.driver.get("http://localhost:5000/")
        self.driver.set_window_size(914, 1063)
        self.driver.find_element(By.LINK_TEXT, "mala").click()
        self.driver.find_element(By.CSS_SELECTOR, ".col-xl-4").click()
        self.driver.find_element(By.ID, "btnGroupDrop98").click()
        self.driver.find_element(By.LINK_TEXT, "Syntax check").click()
        element = self.driver.find_element(By.LINK_TEXT, "Syntax check")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
